type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
  user: User!
}

type Expense @table {
  amount: Float!
  date: Date!
  description: String!
  createdAt: Timestamp!
  notes: String
  user: User!
  category: Category!
}

type Budget @table {
  amount: Float!
  period: String!
  startDate: Date!
  createdAt: Timestamp!
  endDate: Date
  user: User!
  category: Category
}